import type { Metadata } from "next";
import { geistSans, geistMono } from "./fonts"; // Import from fonts.ts
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";

// geistSans and geistMono are now imported, no need to define here

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // Add the font variables to the html tag for global access
    // The ThemeProvider will still handle applying 'dark' or 'light' class
    <html lang="en" suppressHydrationWarning={true} className={`${geistSans.variable} ${geistMono.variable}`}>
      <head>
        <link
          href="https://fonts.googleapis.com/icon?family=Material+Icons+Outlined"
          rel="stylesheet"
        />
      </head>
      <body
        className="font-sans antialiased" // Use Tailwind's font-sans which now maps to Geist Sans
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
